// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI3cko3aXetwb5Zrued-hRCJmgB7Le2Ig',
    appId: '1:399497500906:ios:16fe3da798bd3003f69f93',
    messagingSenderId: '399497500906',
    projectId: 'web-app-5bccf',
    storageBucket: 'web-app-5bccf.firebasestorage.app',
    iosBundleId: 'com.example.storeSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDI3cko3aXetwb5Zrued-hRCJmgB7Le2Ig',
    appId: '1:399497500906:ios:16fe3da798bd3003f69f93',
    messagingSenderId: '399497500906',
    projectId: 'web-app-5bccf',
    storageBucket: 'web-app-5bccf.firebasestorage.app',
    iosBundleId: 'com.example.storeSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYPctfUevt5oR-ZodjNTwQ8vX3aPyi5iM',
    appId: '1:399497500906:web:2d3bd94e18022ec5f69f93',
    messagingSenderId: '399497500906',
    projectId: 'web-app-5bccf',
    authDomain: 'web-app-5bccf.firebaseapp.com',
    storageBucket: 'web-app-5bccf.firebasestorage.app',
    measurementId: 'G-7VYVKJ4SZE',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYPctfUevt5oR-ZodjNTwQ8vX3aPyi5iM',
    appId: '1:399497500906:web:2d3bd94e18022ec5f69f93',
    messagingSenderId: '399497500906',
    projectId: 'web-app-5bccf',
    authDomain: 'web-app-5bccf.firebaseapp.com',
    storageBucket: 'web-app-5bccf.firebasestorage.app',
    measurementId: 'G-7VYVKJ4SZE',
  );
}
